import 'dart:convert';

import 'package:api_flutter/json_model/test_model.dart';

List<Temperatures> temperaturesFromJson(String str) => List<Temperatures>.from(json.decode(str).map((x) => Temperatures.fromJson(x)));

String temperaturesToJson(List<Temperatures> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class Temperatures {
    int? userId;
    int? id;
    String? title;
    String? body;

    Temperatures({
        this.userId,
        this.id,
        this.title,
        this.body,
    });

    factory Temperatures.fromJson(Map<String, dynamic> json) => Temperatures(
        userId: json["userId"],
        id: json["id"],
        title: json["title"],
        body: json["body"],
    );

    Map<String, dynamic> toJson() => {
        "userId": userId,
        "id": id,
        "title": title,
        "body": body,
    };
}
// 
// 
List<Autogenerated> AutogeneratedFromJson(String str) => List<Autogenerated>.from(json.decode(str).map((x) => Autogenerated.fromJson(x)));
 String AutogeneratedToJson(List<Autogenerated> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));
class Autogenerated {    
  int? userId;
  int? id;
  String? title;
  String? body;

  Autogenerated({this.userId, this.id, this.title, this.body});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    userId = json['userId'];
    id = json['id'];
    title = json['title'];
    body = json['body'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['userId'] = this.userId;
    data['id'] = this.id;
    data['title'] = this.title;
    data['body'] = this.body;
    return data;
  }
}
// 
// Constrectr 
List<Constrectr> ConstrectrFromJson(String str) => List<Constrectr>.from(json.decode(str).map((x) =>Constrectr.fromJson(x)));
 String ConstrectrToJson(List<Constrectr> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));
class Constrectr {
  int? userId;
  int? id;
  String? title;
  String? body;

  Constrectr({this.userId, this.id, this.title, this.body});

  Constrectr.fromJson(Map<dynamic, dynamic> json) {
    userId = json['userId'];
    id = json['id'];
    title = json['title'];
    body = json['body'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['userId'] = this.userId;
    data['id'] = this.id;
    data['title'] = this.title;
    data['body'] = this.body;
    return data;
  }
}